### ISSUE TITLE
ID Issue

### ISSUE THREAD

**Issue by rocknroll17** [Kim-s-pirate/planner_server#11]
## Problem
In my thinking there would be serious problem if we approach some data by title or name. Cause' if someone is dealing with some data but changes object's attribute at the same time. There will be fatal error until refresh the page.
## Solution
So we have to make almost of end-points to query some data with id.
## TO-DO
- [x] Make id with hash
- [x] Replace all the end-points which uses its name for query on database.
- [x] Create service code that query data with its id
